FROM arm32v7/python:3.7-slim-buster

WORKDIR /home/pi/WorkSpace/edgeApp

RUN apt-get update && apt-get install -y python3

ENV PATH="/usr/local/bin/python3:${PATH}"

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY . .

CMD [ "python3", "-u", "./main.py" ]